tnc1997/azure-app-configuration-emulator

src/AzureAppConfigurationEmulator/Constants/KeyFilter.cs, src/AzureAppConfigurationEmulator/Constants/LabelFilter.cs, src/AzureAppConfigurationEmulator/Extensions/StringExtensions.cs, src/AzureAppConfigurationEmulator/Handlers/KeyValueHandler.cs, src/AzureAppConfigurationEmulator/Program.cs, src/AzureAppConfigurationEmulator/Results/KeyValueResult.cs
=> feat: add set configuration setting endpoint

src/AzureAppConfigurationEmulator/AzureAppConfigurationEmulator.csproj, src/AzureAppConfigurationEmulator/Extensions/QueryableExtensions.cs, src/AzureAppConfigurationEmulator/Extensions/StringExtensions.cs, src/AzureAppConfigurationEmulator/Handlers/KeyValueHandler.cs, src/AzureAppConfigurationEmulator/Program.cs, src/AzureAppConfigurationEmulator/Results/InvalidCharacterResult.cs, src/AzureAppConfigurationEmulator/Results/KeyValueSetResult.cs, src/AzureAppConfigurationEmulator/Results/TooManyValuesResult.cs
=> feat: add list configuration settings endpoint

README.md, src/AzureAppConfigurationEmulator/Handlers/KeyValueHandler.cs, src/AzureAppConfigurationEmulator/Program.cs
=> feat: add get configuration setting endpoint

README.md, src/AzureAppConfigurationEmulator/Handlers/KeyValueHandler.cs, src/AzureAppConfigurationEmulator/Program.cs
=> feat: add delete configuration setting endpoint

README.md, src/AzureAppConfigurationEmulator/Handlers/KeyValueHandler.cs, src/AzureAppConfigurationEmulator/Handlers/LockHandler.cs, src/AzureAppConfigurationEmulator/Program.cs, src/AzureAppConfigurationEmulator/Results/ReadOnlyResult.cs
=> feat: add lock configuration setting endpoint

README.md, src/AzureAppConfigurationEmulator/Handlers/LockHandler.cs, src/AzureAppConfigurationEmulator/Program.cs
=> feat: add unlock configuration setting endpoint

README.md, src/AzureAppConfigurationEmulator/Handlers/KeyHandler.cs, src/AzureAppConfigurationEmulator/Program.cs, src/AzureAppConfigurationEmulator/Results/KeySetResult.cs
=> feat: add list configuration setting keys endpoint

README.md, src/AzureAppConfigurationEmulator/Handlers/LabelHandler.cs, src/AzureAppConfigurationEmulator/Program.cs, src/AzureAppConfigurationEmulator/Results/LabelSetResult.cs
=> feat: add list configuration setting labels endpoint

src/AzureAppConfigurationEmulator/Handlers/KeyHandler.cs, src/AzureAppConfigurationEmulator/Handlers/LabelHandler.cs
=> fix: distinct configuration setting keys and labels

src/AzureAppConfigurationEmulator/Handlers/LabelHandler.cs, src/AzureAppConfigurationEmulator/Results/LabelSetResult.cs
=> fix: normalize nulls from list labels endpoint

README.md, src/AzureAppConfigurationEmulator/Dockerfile, src/AzureAppConfigurationEmulator/Extensions/HostingExtensions.cs, src/AzureAppConfigurationEmulator/Program.cs, src/AzureAppConfigurationEmulator/Properties/launchSettings.json
=> feat: add support for https using ssl certificate

.run/AzureAppConfigurationEmulator_Dockerfile.run.xml, README.md, src/AzureAppConfigurationEmulator/Authentication/HmacConfigureOptions.cs, src/AzureAppConfigurationEmulator/Authentication/HmacDefaults.cs, src/AzureAppConfigurationEmulator/Authentication/HmacExtensions.cs, src/AzureAppConfigurationEmulator/Authentication/HmacHandler.cs, src/AzureAppConfigurationEmulator/Authentication/HmacOptions.cs, src/AzureAppConfigurationEmulator/Program.cs, src/AzureAppConfigurationEmulator/appsettings.Development.json, src/AzureAppConfigurationEmulator/appsettings.json
=> feat: add required hmac authentication scheme

AzureAppConfigurationEmulator.sln, README.md, src/AzureAppConfigurationEmulator/Entities/ConfigurationSetting.cs, src/AzureAppConfigurationEmulator/Handlers/KeyValueHandler.cs, src/AzureAppConfigurationEmulator/Handlers/LockHandler.cs, src/AzureAppConfigurationEmulator/Migrations/20231001000000_InitialCreate.Designer.cs, src/AzureAppConfigurationEmulator/Migrations/20231001000000_InitialCreate.cs, src/AzureAppConfigurationEmulator/Migrations/ApplicationDbContextModelSnapshot.cs, src/AzureAppConfigurationEmulator/Results/KeyValueResult.cs, src/AzureAppConfigurationEmulator/Results/KeyValueSetResult.cs, src/AzureAppConfigurationEmulator/Results/NotModifiedResult.cs, src/AzureAppConfigurationEmulator/Results/PreconditionFailedResult.cs, tests/AzureAppConfigurationEmulator.Tests/AzureAppConfigurationEmulator.Tests.csproj, tests/AzureAppConfigurationEmulator.Tests/Handlers/KeyValueHandlerTests.cs, tests/AzureAppConfigurationEmulator.Tests/Handlers/LockHandlerTests.cs
=> feat: add support for etags and the associated headers

src/AzureAppConfigurationEmulator/Handlers/KeyValueHandler.cs
=> fix: last modified and etag not updated

src/AzureAppConfigurationEmulator/Contexts/ApplicationDbContext.cs, src/AzureAppConfigurationEmulator/Entities/ConfigurationSettingRevision.cs, src/AzureAppConfigurationEmulator/Migrations/20231001000000_InitialCreate.Designer.cs, src/AzureAppConfigurationEmulator/Migrations/20231001000000_InitialCreate.cs, src/AzureAppConfigurationEmulator/Migrations/ApplicationDbContextModelSnapshot.cs, src/AzureAppConfigurationEmulator/Repositories/ConfigurationSettingRepository.cs
=> feat: add configuration setting revision entity

src/AzureAppConfigurationEmulator/Handlers/KeyValueHandler.cs
=> fix: encoding of etag from utf-8 to base64

src/AzureAppConfigurationEmulator/Results/KeyValueResult.cs
=> fix: add etag header to key value result

tests/AzureAppConfigurationEmulator.Tests/Handlers/KeyValueHandlerTests.cs, tests/AzureAppConfigurationEmulator.Tests/Handlers/LockHandlerTests.cs
=> test: update key value handler

README.md, src/AzureAppConfigurationEmulator/Authentication/HmacHandler.cs, src/AzureAppConfigurationEmulator/AzureAppConfigurationEmulator.csproj, src/AzureAppConfigurationEmulator/Components/Pages/ConfigurationExplorer.razor, src/AzureAppConfigurationEmulator/Components/Pages/FeatureManager.razor, src/AzureAppConfigurationEmulator/Factories/DbCommandFactory.cs, src/AzureAppConfigurationEmulator/Handlers/KeyHandler.cs, src/AzureAppConfigurationEmulator/Handlers/KeyValueHandler.cs, src/AzureAppConfigurationEmulator/Handlers/LabelHandler.cs, src/AzureAppConfigurationEmulator/Handlers/LockHandler.cs, src/AzureAppConfigurationEmulator/Program.cs, src/AzureAppConfigurationEmulator/Repositories/ConfigurationSettingRepository.cs, src/AzureAppConfigurationEmulator/Repositories/IConfigurationSettingRepository.cs, src/AzureAppConfigurationEmulator/Telemetry.cs, tests/AzureAppConfigurationEmulator.Tests/Repositories/ConfigurationSettingRepositoryTests.cs
=> feat: integrate with opentelemetry

src/AzureAppConfigurationEmulator/Components/AzureTextField.razor, src/AzureAppConfigurationEmulator/Components/ConfigurationSettingEditDialog.razor, src/AzureAppConfigurationEmulator/Components/Pages/ConfigurationExplorer.razor
=> feat: add configuration setting editing

AzureAppConfigurationEmulator.sln, src/AzureAppConfigurationEmulator.Common/Abstractions/IConfigurationSettingFactory.cs, src/AzureAppConfigurationEmulator.Common/Models/ConfigurationSetting.cs, src/AzureAppConfigurationEmulator.Common/Results/ConfigurationSettingResult.cs, src/AzureAppConfigurationEmulator.Common/Results/ConfigurationSettingsResult.cs, src/AzureAppConfigurationEmulator.ConfigurationSettings/ConfigurationSettingFactory.cs, src/AzureAppConfigurationEmulator.ConfigurationSettings/ConfigurationSettingHandler.cs, src/AzureAppConfigurationEmulator.ConfigurationSettings/ConfigurationSettingRepository.cs, src/AzureAppConfigurationEmulator.Keys/KeysResult.cs, src/AzureAppConfigurationEmulator.Labels/LabelsResult.cs, src/AzureAppConfigurationEmulator/Program.cs, tests/AzureAppConfigurationEmulator.Common.Tests/AzureAppConfigurationEmulator.Common.Tests.csproj, tests/AzureAppConfigurationEmulator.Common.Tests/Results/ConfigurationSettingResultTests.cs, tests/AzureAppConfigurationEmulator.Common.Tests/Results/ConfigurationSettingsResultTests.cs, tests/AzureAppConfigurationEmulator.ConfigurationSettings.Tests/ConfigurationSettingRepositoryTests.cs
=> fix: serialize tags as empty object if null

src/AzureAppConfigurationEmulator.Data.Sqlite/SqliteDbParameterFactory.cs, tests/AzureAppConfigurationEmulator.Data.Sqlite.Tests/AzureAppConfigurationEmulator.Data.Sqlite.Tests.csproj, tests/AzureAppConfigurationEmulator.Data.Sqlite.Tests/SqliteDbParameterFactoryTests.cs
=> fix: tags incorrectly serialized as dictionary to string

src/AzureAppConfigurationEmulator.Authentication.Hmac/HmacAuthenticatingHttpMessageHandler.cs, src/AzureAppConfigurationEmulator.Authentication.Hmac/Telemetry.cs, src/AzureAppConfigurationEmulator.Common/Abstractions/IConfigurationClient.cs, src/AzureAppConfigurationEmulator.Common/Clients/ConfigurationClient.cs, src/AzureAppConfigurationEmulator.Common/Headers/LinkHeaderValue.cs, src/AzureAppConfigurationEmulator/Components/AzureInputDate.razor, src/AzureAppConfigurationEmulator/Components/AzureInputRadioGroup.razor, src/AzureAppConfigurationEmulator/Components/AzureInputSelect.razor, src/AzureAppConfigurationEmulator/Components/AzureInputText.razor, src/AzureAppConfigurationEmulator/Components/ImportExportContentTypeInputSelect.razor, src/AzureAppConfigurationEmulator/Components/ImportExportFileTypeInputSelect.razor, src/AzureAppConfigurationEmulator/Components/ImportExportLabelFilterInputSelect.razor, src/AzureAppConfigurationEmulator/Components/ImportExportOperationInputRadioGroup.razor, src/AzureAppConfigurationEmulator/Components/ImportExportSeparatorInputSelect.razor, src/AzureAppConfigurationEmulator/Components/ImportExportSourceServiceInputSelect.razor, src/AzureAppConfigurationEmulator/Components/Pages/ImportExport.razor, src/AzureAppConfigurationEmulator/Program.cs
=> feat: add import from azure app configuration

src/AzureAppConfigurationEmulator.ConfigurationSettings/ConfigurationSettingHandler.cs
=> fix: incorrect deserialization of set input

src/AzureAppConfigurationEmulator/Components/Pages/ConfigurationExplorer.razor, src/AzureAppConfigurationEmulator/Components/Pages/FeatureManager.razor
=> fix: edited configuration settings move to the bottom

src/AzureAppConfigurationEmulator/Components/Pages/ConfigurationExplorer.razor
=> refactor: order configuration settings by key

src/AzureAppConfigurationEmulator/Components/Pages/FeatureManager.razor
=> refactor: order feature flags by name

src/AzureAppConfigurationEmulator/Components/Pages/ConfigurationExplorer.razor, src/AzureAppConfigurationEmulator/Components/Pages/FeatureManager.razor
=> fix: search query case sensitivity
